Resources:
  BookingsDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.BookingsDB}
      AttributeDefinitions:
        - AttributeName: bokkingId
          AttributeType: S
        - AttributeName: listingId
          AttributeType: S
      KeySchema:
        - AttributeName: bokkingId
          KeyType: HASH
        - AttributeName: listingId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
